# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

podSecurityContext:
  runAsUser: 100
  runAsGroup: 1000
  fsGroup: 1000
  supplementalGroups: [1000]

containerSecurityContext:
  runAsUser: 100
  runAsGroup: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  capabilities:
    drop:
    - ALL

topologyKey: topology.kubernetes.io/zone

jumper:
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
      - ALL

issuerService:
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
      - ALL

plugins:
  containerSecurityContext:
    runAsUser: 100
    runAsGroup: 1000
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
      - ALL

jobs:
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
      - ALL

postgresql:
  podSecurityContext:
    fsGroup: 999
    supplementalGroups: [999]    

  containerSecurityContext:
    runAsGroup: 999
    runAsUser: 999
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
      - ALL

global:
  ingress:
    ingressClassName: nginx