apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pipeline-metadata
  labels: {{ include "kong.labels" $ | nindent 4 }}
data:
  chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  {{- if not (empty .Values.global.metadata.pipeline) -}}
  {{- .Values.global.metadata.pipeline | toYaml| nindent 2 }}
  {{- end -}}