
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-servers
  labels: {{- include "kong.labels" $ | nindent 4 }}
data:
  servers.conf: |
      # Kong Prometheus Exporter
      server {
          server_name kong_prometheus_exporter;
          listen 0.0.0.0:{{ .Values.plugins.prometheus.port | default 9542 }};
          access_log off;

          location {{ .Values.plugins.prometheus.path | default "/metrics" }} {
              default_type text/plain;
              content_by_lua_block {
                  local prometheus = require "kong.plugins.prometheus.exporter"
                  prometheus:collect()
              }
          }

          location /nginx_status {
              internal;
              stub_status;
          }
      }
