apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy
  labels: {{ include "kong.labels" $ | nindent 4 }}
spec:
  selector: {{ include "kong.selector" $ | nindent 4 }}
  ports:
{{- if .Values.proxy.tls.enabled }}
  - name: proxy-ssl
    port: 8443
    targetPort: 8443
{{- else }}
  - name: proxy
    port: 8000
    targetPort: 8000
{{- end }}
    protocol: TCP