# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

global:
  metadata:
    pipeline: {}

  platform: kubernetes
  #pathToSecret: "path/to/secret" 
  #storageClassName: gp2
  
  passwordRules:
    enabled: false
    length: 12
    mustMatch:
    - '[a-z]'
    - '[A-Z]'
    - '[0-9]'
    - '[^a-zA-Z0-9]' 

  labels:
    # fluentd label
    tardis.telekom.de/group: tardis

  imagePullSecrets: []
  #- name: mtr-tif-public
  #  registry: https://mtr.external.otc.telekomcloud.com
  #  username: changeme
  #  password: changeme

  #image:
    #force: false

  imagePullPolicy: IfNotPresent

  database:
    location: local
    # Set host if you use an external database or service name is not sufficient
    #host: ''
    #port: 5432
    database: sso
    username: sso
    password: changeme

  failOnUnsetValues: true

  nameOverride: ""
  fullnameOverride: ""

# You can force using a specific image here:
#image:
  #repository: mtr.devops.telekom.de
  #organization: tardis-common
  #name: postgres
  #tag: 12.3-debian
# Or use the flattened string form:
#image: mtr.devops.telekom.de/tardis-common/postgres:12.3-debian
#imagePullPolicy: IfNotPresent


#podSecurityContext:
  #fsGroup: 999
  #supplementalGroups: 999

#containerSecurityContext: {}

# database admin credentials
#adminPassword: "changeme"

# maximum number of client connections
maxConnections: "100"

# memory dedicated to PostgreSQL for caching data
sharedBuffers: "32MB"

# maximum number of transactions that can be in the "prepared" state simultaneously
# setting this parameter to zero (default) disables the prepared-transaction feature
maxPreparedTransactions: "0"

resources:
  limits:
    cpu: 100m
    memory: 500Mi
  requests:
    cpu: 20m
    memory: 200Mi

persistence:
  keepOnDelete: false
  #storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
  #mountDir: '/var/lib/postgresql/data'

deployment:
  annotations: {}
